package com.automationstudio.ai;

import com.automationstudio.workflow.WorkflowDefinition;
import com.automationstudio.workflow.WorkflowService;
import com.automationstudio.workflow.WorkflowValidator;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.stereotype.Service;

/** Natural-language to workflow JSON with a 2-round validation repair loop. */
@Service
public class WorkflowGenerationService {

  private static final String SYSTEM = """
      You design automation workflows. Reply with STRICT JSON only, no prose, no fences.
      Schema: {"version":1,"name":string,"description":string,
      "nodes":[{"id":"[a-z0-9_]+","type":one of manual_trigger|http_request|llm|condition|transform|output|app_action|app_trigger,
      "name":string,"position":{"x":int,"y":int},"config":{},"settings":{"onError":"stop|continue|route","retries":0-5,"timeoutMs":ms}}],
      "edges":[{"id":string,"source":node id,"target":node id,"sourceHandle":"true|false for condition"}],
      "pinData":{}}.
      Rules: exactly one manual_trigger; DAG only; refs like {{http_1.output.body}} must point upstream;
      condition.expression uses bare refs (no braces), e.g. trigger_1.output.score >= 50;
      llm nodes use outputFormat json + jsonShape before a condition; use {{credentials.NAME}} placeholders, never real keys;
      only keyless public URLs you know (api.open-meteo.com, jsonplaceholder.typicode.com) or leave url blank;
      prefer app_action with a real app name from the catalog only if the user names that app.
      Example nodes: trigger_1 manual_trigger; http_1 http_request GET open-meteo;
      llm_1 llm prompt with {{http_1.output.body}} outputFormat json; condition_1 on llm_1.output.json.<field>;
      output_yes/output_no outputs with sourceHandle true/false.
      """;

  private final LlmRouter router;
  private final WorkflowValidator validator;
  private final WorkflowService workflows;
  private final ObjectMapper json;

  public WorkflowGenerationService(
      LlmRouter router, WorkflowValidator validator, WorkflowService workflows, ObjectMapper json) {
    this.router = router;
    this.validator = validator;
    this.workflows = workflows;
    this.json = json;
  }

  public Map<String, Object> generate(String prompt) {
    List<String> attempts = new ArrayList<>();
    String feedback = "";
    WorkflowDefinition def = null;
    WorkflowValidator.ValidationResult result = null;
    for (int round = 0; round <= 2; round++) {
      String user = round == 0 ? prompt
          : prompt + "\n\nPrevious output had these validation errors, fix them:\n" + feedback;
      LlmRouter.LlmAnswer answer = router.chat(user, SYSTEM, true, false);
      attempts.add(answer.tier() + "/" + answer.model());
      try {
        def = json.readValue(String.valueOf(answer.text()), WorkflowDefinition.class);
      } catch (Exception e) {
        // try the parsed json object if the model returned structured output
        try {
          def = json.convertValue(answer.json(), WorkflowDefinition.class);
        } catch (Exception ex) {
          feedback = "Output was not valid JSON: " + e.getMessage();
          continue;
        }
      }
      result = validator.validate(def);
      if ("VALID".equals(result.status())) break;
      StringBuilder sb = new StringBuilder();
      for (var issue : result.errors()) {
        sb.append(issue.code()).append(" node=").append(issue.nodeId())
            .append(" path=").append(issue.path()).append(": ").append(issue.message()).append("\n");
      }
      feedback = sb.toString();
    }
    if (def == null) {
      return Map.of("status", "FAILED", "issues", List.of(Map.of("message", feedback)));
    }
    var saved = workflows.create(def);
    List<Map<String, Object>> issues = result == null ? List.of()
        : result.issues().stream()
            .map(i -> Map.<String, Object>of("code", i.code(), "nodeId",
                i.nodeId() == null ? "" : i.nodeId(), "message", i.message()))
            .toList();
    Map<String, Object> out = new java.util.LinkedHashMap<>();
    out.put("id", saved.id);
    out.put("workflow", def);
    out.put("status", saved.status);
    out.put("issues", issues);
    out.put("generatedBy", attempts);
    if (attempts.stream().anyMatch(a -> a.startsWith("local-"))) {
      out.put("warning", "generated by local model, review carefully");
    }
    return out;
  }
}
