export interface PieceApp {
  app: string;
  displayName: string;
  category: string;
  enabled: boolean;
  operations: string[];
  triggers: string[];
}

export const PIECE_APPS: PieceApp[] = [
  { app: "openai", displayName: "OpenAI", category: "ai", enabled: true, operations: ["list_models", "chat"], triggers: [] },
  { app: "anthropic", displayName: "Anthropic Claude", category: "ai", enabled: true, operations: ["list_models", "message"], triggers: [] },
  { app: "gemini", displayName: "Google Gemini", category: "ai", enabled: true, operations: ["list_models", "generate"], triggers: [] },
  { app: "groq", displayName: "Groq", category: "ai", enabled: true, operations: ["list_models", "chat"], triggers: [] },
  { app: "mistral", displayName: "Mistral", category: "ai", enabled: true, operations: ["list_models", "chat"], triggers: [] },
  { app: "cohere", displayName: "Cohere", category: "ai", enabled: true, operations: ["list_models", "chat"], triggers: [] },
  { app: "huggingface", displayName: "Hugging Face", category: "ai", enabled: true, operations: ["infer"], triggers: [] },
  { app: "perplexity", displayName: "Perplexity", category: "ai", enabled: true, operations: ["list_models", "chat"], triggers: [] },
  { app: "azure_openai", displayName: "Azure OpenAI", category: "ai", enabled: true, operations: ["chat"], triggers: [] },
  { app: "ollama", displayName: "Ollama", category: "ai", enabled: true, operations: ["tags", "generate"], triggers: [] },
  { app: "openrouter", displayName: "OpenRouter", category: "ai", enabled: true, operations: ["list_models", "chat"], triggers: [] },
  { app: "bedrock", displayName: "AWS Bedrock", category: "ai", enabled: true, operations: ["invoke"], triggers: [] },
  { app: "slack", displayName: "Slack", category: "communication", enabled: true, operations: ["post_message", "list_channels"], triggers: ["new_message"] },
  { app: "discord", displayName: "Discord", category: "communication", enabled: true, operations: ["send_message", "get_channel"], triggers: [] },
  { app: "telegram", displayName: "Telegram", category: "communication", enabled: true, operations: ["send_message"], triggers: ["updates"] },
  { app: "whatsapp", displayName: "WhatsApp Business", category: "communication", enabled: true, operations: ["send_message"], triggers: [] },
  { app: "teams", displayName: "MS Teams", category: "communication", enabled: true, operations: ["post_message"], triggers: [] },
  { app: "twilio", displayName: "Twilio", category: "communication", enabled: true, operations: ["send_sms"], triggers: [] },
  { app: "sendgrid", displayName: "SendGrid", category: "communication", enabled: true, operations: ["send_mail", "list_templates"], triggers: [] },
  { app: "smtp", displayName: "SMTP", category: "communication", enabled: true, operations: ["send_email"], triggers: [] },
  { app: "mattermost", displayName: "Mattermost", category: "communication", enabled: true, operations: ["create_post", "list_channels"], triggers: [] },
  { app: "gmail", displayName: "Gmail", category: "communication", enabled: false, operations: ["list_messages"], triggers: [] },
  { app: "outlook", displayName: "Outlook", category: "communication", enabled: false, operations: ["list_messages"], triggers: [] },
  { app: "postgres", displayName: "PostgreSQL", category: "database", enabled: true, operations: ["query"], triggers: [] },
  { app: "mysql", displayName: "MySQL", category: "database", enabled: true, operations: ["query"], triggers: [] },
  { app: "mongodb", displayName: "MongoDB", category: "database", enabled: true, operations: ["find"], triggers: [] },
  { app: "redis", displayName: "Redis", category: "database", enabled: true, operations: ["get"], triggers: [] },
  { app: "sqlite", displayName: "SQLite", category: "database", enabled: true, operations: ["query"], triggers: [] },
  { app: "mssql", displayName: "SQL Server", category: "database", enabled: true, operations: ["query"], triggers: [] },
  { app: "dropbox", displayName: "Dropbox", category: "storage", enabled: true, operations: ["list_folder", "get_metadata", "upload"], triggers: [] },
  { app: "box", displayName: "Box", category: "storage", enabled: true, operations: ["list_folder", "get_file"], triggers: [] },
  { app: "s3", displayName: "AWS S3", category: "storage", enabled: true, operations: ["list_objects", "get_object"], triggers: [] },
  { app: "azure_blob", displayName: "Azure Blob", category: "storage", enabled: true, operations: ["list_blobs"], triggers: [] },
  { app: "drive", displayName: "Google Drive", category: "storage", enabled: false, operations: ["list_files"], triggers: [] },
  { app: "sheets", displayName: "Google Sheets", category: "storage", enabled: false, operations: ["read"], triggers: [] },
  { app: "docs", displayName: "Google Docs", category: "storage", enabled: false, operations: ["get_doc"], triggers: [] },
  { app: "gcalendar", displayName: "Google Calendar", category: "storage", enabled: false, operations: ["list_events"], triggers: [] },
  { app: "onedrive", displayName: "OneDrive", category: "storage", enabled: false, operations: ["list_root"], triggers: [] },
  { app: "gcs", displayName: "Google Cloud Storage", category: "storage", enabled: false, operations: ["list_objects"], triggers: [] },
  { app: "github", displayName: "GitHub", category: "developer", enabled: true, operations: ["get_repo", "list_issues", "create_issue"], triggers: ["new_issue"] },
  { app: "gitlab", displayName: "GitLab", category: "developer", enabled: true, operations: ["get_project", "list_issues", "create_issue"], triggers: ["new_issue"] },
  { app: "bitbucket", displayName: "Bitbucket", category: "developer", enabled: true, operations: ["get_repo", "list_issues"], triggers: [] },
  { app: "jira", displayName: "Jira", category: "developer", enabled: true, operations: ["get_issue", "create_issue"], triggers: ["new_issue"] },
  { app: "linear", displayName: "Linear", category: "developer", enabled: true, operations: ["list_issues"], triggers: [] },
  { app: "trello", displayName: "Trello", category: "developer", enabled: true, operations: ["get_board", "create_card"], triggers: ["new_card"] },
  { app: "clickup", displayName: "ClickUp", category: "developer", enabled: true, operations: ["get_task", "create_task"], triggers: ["new_task"] },
  { app: "notion", displayName: "Notion", category: "developer", enabled: true, operations: ["query_db", "create_page"], triggers: ["new_page"] },
  { app: "graphql", displayName: "GraphQL", category: "web", enabled: true, operations: ["execute"], triggers: [] },
  { app: "rss", displayName: "RSS", category: "web", enabled: true, operations: ["get_feed"], triggers: [] },
  { app: "soap", displayName: "SOAP", category: "web", enabled: true, operations: ["call"], triggers: [] },
  { app: "shopify", displayName: "Shopify", category: "ecommerce", enabled: true, operations: ["list_products", "create_product"], triggers: ["new_product"] },
  { app: "woocommerce", displayName: "WooCommerce", category: "ecommerce", enabled: true, operations: ["list_orders", "create_product"], triggers: [] },
  { app: "stripe", displayName: "Stripe", category: "ecommerce", enabled: true, operations: ["list_customers", "create_payment"], triggers: ["new_customer"] },
  { app: "paypal", displayName: "PayPal", category: "ecommerce", enabled: true, operations: ["get_order"], triggers: [] },
  { app: "square", displayName: "Square", category: "ecommerce", enabled: true, operations: ["list_payments"], triggers: [] },
  { app: "magento", displayName: "Magento", category: "ecommerce", enabled: true, operations: ["list_orders"], triggers: [] },
  { app: "hubspot", displayName: "HubSpot", category: "crm", enabled: true, operations: ["list_contacts", "create_contact"], triggers: ["new_contact"] },
  { app: "pipedrive", displayName: "Pipedrive", category: "crm", enabled: true, operations: ["list_deals", "create_deal"], triggers: [] },
  { app: "mailchimp", displayName: "Mailchimp", category: "crm", enabled: true, operations: ["list_members", "add_member"], triggers: [] },
  { app: "brevo", displayName: "Brevo", category: "crm", enabled: true, operations: ["send_email", "create_contact"], triggers: [] },
  { app: "activecampaign", displayName: "ActiveCampaign", category: "crm", enabled: true, operations: ["list_contacts", "create_contact"], triggers: [] },
  { app: "klaviyo", displayName: "Klaviyo", category: "crm", enabled: true, operations: ["list_profiles", "create_profile"], triggers: [] },
  { app: "intercom", displayName: "Intercom", category: "crm", enabled: true, operations: ["list_contacts", "create_contact"], triggers: [] },
  { app: "salesforce", displayName: "Salesforce", category: "crm", enabled: false, operations: ["query"], triggers: [] },
  { app: "zoho", displayName: "Zoho CRM", category: "crm", enabled: false, operations: ["list_contacts"], triggers: [] },
  { app: "facebook", displayName: "Facebook", category: "social", enabled: false, operations: ["get_profile"], triggers: [] },
  { app: "instagram", displayName: "Instagram", category: "social", enabled: false, operations: ["get_profile"], triggers: [] },
  { app: "linkedin", displayName: "LinkedIn", category: "social", enabled: false, operations: ["get_profile"], triggers: [] },
  { app: "x", displayName: "X (Twitter)", category: "social", enabled: false, operations: ["get_user"], triggers: [] },
  { app: "youtube", displayName: "YouTube", category: "social", enabled: false, operations: ["list_videos"], triggers: [] },
  { app: "reddit", displayName: "Reddit", category: "social", enabled: false, operations: ["get_profile"], triggers: [] },
  { app: "tiktok", displayName: "TikTok", category: "social", enabled: false, operations: ["get_profile"], triggers: [] },
  { app: "zapier", displayName: "Zapier", category: "productivity", enabled: true, operations: ["trigger"], triggers: [] },
  { app: "airtable", displayName: "Airtable", category: "productivity", enabled: true, operations: ["list_records", "create_record"], triggers: ["new_record"] },
  { app: "calendly", displayName: "Calendly", category: "productivity", enabled: true, operations: ["list_events"], triggers: ["new_event"] },
  { app: "todoist", displayName: "Todoist", category: "productivity", enabled: true, operations: ["list_tasks", "create_task"], triggers: [] },
  { app: "asana", displayName: "Asana", category: "productivity", enabled: true, operations: ["list_tasks", "create_task"], triggers: [] },
  { app: "monday", displayName: "Monday.com", category: "productivity", enabled: true, operations: ["list_boards"], triggers: [] },
  { app: "excel", displayName: "MS Excel", category: "productivity", enabled: false, operations: ["list_worksheets"], triggers: [] },
  { app: "gsheets_app", displayName: "Google Sheets App", category: "productivity", enabled: false, operations: ["read"], triggers: [] },
  { app: "homeassistant", displayName: "Home Assistant", category: "other", enabled: true, operations: ["get_states", "call_service"], triggers: [] },
  { app: "mqtt", displayName: "MQTT", category: "other", enabled: true, operations: ["publish"], triggers: [] },
  { app: "wordpress", displayName: "WordPress", category: "other", enabled: true, operations: ["list_posts", "create_post"], triggers: [] },
  { app: "steam", displayName: "Steam", category: "other", enabled: true, operations: ["get_player"], triggers: [] },
  { app: "plex", displayName: "Plex", category: "other", enabled: true, operations: ["list_libraries"], triggers: [] },
  { app: "hue", displayName: "Philips Hue", category: "other", enabled: true, operations: ["list_lights"], triggers: [] },
];
